# Generated by Django 4.2.7 on 2023-12-04 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubjectTeacher',
            fields=[
                ('type_lesson', models.CharField(max_length=15)),
                ('day', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('group_subjects', models.ManyToManyField(related_name='teachers', to='myapp.groupsubjectteacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.group')),
            ],
        ),
        migrations.AddField(
            model_name='groupsubjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.subject'),
        ),
        migrations.AddField(
            model_name='groupsubjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsubjectteacher',
            unique_together={('group', 'subject', 'teacher', 'type_lesson')},
        ),
    ]
